public class Main {
    public static void main(String[] args) {
        System.out.println("Задание 1");
        int cat = 5;
        System.out.println("Кошек " + cat +" шт");
        byte dog = 20;
        System.out.println("Собак " + dog + " шт");
        short tiger = 10;
        System.out.println("Тигр " + tiger + " шт");
        long mouse = 16;
        System.out.println("Мышь " + mouse + " шт");
        float rabbit = 8;
        System.out.println("Кролик " + rabbit + " шт");
        double bear = 28;
        System.out.println("Медведь " + bear + " шт");

        System.out.println("Задание 2");
        int a = 569;
        System.out.println(a);
        byte b = 67;
        System.out.println(b);
        short c = -159;
        System.out.println(c);
        long l = 987678965549L;
        System.out.println(l);
        float e = 2.786f;
        System.out.println(e);
        double i = 27.12;
        System.out.println(i);

        System.out.println("Задание 3");
        byte lyudmilaPavlovna = 23;
        System.out.println(lyudmilaPavlovna + " Ученика у Людмилы Павловны ");
        short annaSergeyevna = 27;
        System.out.println(annaSergeyevna + " Учеников у Анны Сергивны");
        int ekaterinaAndreevna = 30;
        System.out.println(ekaterinaAndreevna + " Учеников у Екатерины Андреевны");
        long sheets = 480;
        System.out.println(sheets + " Листов бумаги купили 3 учительницы");
        long students = lyudmilaPavlovna + annaSergeyevna + ekaterinaAndreevna;
        System.out.println("Всего " + students + " учеников с 3-х классов");
        long paper = sheets / students;
        System.out.println("На каждого ученика рассчитано " + paper + " листов бумаги");

        System.out.println("Задание 4");
        int bottles = 16;
        System.out.println(bottles + " Бутылок производит машина за указанное время");
        int specifiedTime = 2;
        System.out.println(specifiedTime + " Минуты" + " указанное время производства 16 бутылок");
        int time = bottles / specifiedTime;
        System.out.println(time + " Бутылок производит машина в минуту");
        int minutes = 20;
        System.out.println("Выясняем сколько будет произведено за " + minutes + " минут");
        int bottlesPerMinute = time * minutes;
        System.out.println(bottlesPerMinute + " Бутылок будет произведенно машиной за 20 минут");
        int day = 1440;
        System.out.println(day + " минут в сутках");
        int timePerDay = time * day;
        System.out.println(timePerDay + " Бутылок было произведено за сутки");
        int threeDays = 4320;
        System.out.println(threeDays + " Минут в 3-х сутках");
        int producedThreeDays = threeDays * time;
        System.out.println(producedThreeDays + " Бутылок было произведено за 3 дня");
        int minutesPerMonth = 43200;
        System.out.println(minutesPerMonth + " Минут в месяце");
        int producedThreeMonths = minutesPerMonth * time;
        System.out.println(producedThreeMonths + " Бутылок произвела машина за месяц");

        System.out.println("Задание 5");
        long totalCansPaint = 120;
        System.out.println(totalCansPaint + " Банок краски всего");
        long whitePaint = 2;
        System.out.println("Нужно банки белой краски на 1 класс " + whitePaint + " шт");
        long brownPaint = 4;
        System.out.println("Нужно банок коричневой краски на 1 класс " + brownPaint + " шт");
        long totalNumberCans = whitePaint + brownPaint;
        System.out.println("Общее количество банок краски на 1 класс " + totalNumberCans + " шт");
        long totalClasses = totalCansPaint / totalNumberCans;
        System.out.println("Количество классов в школе " + totalClasses);
        long allWhitePaint = totalClasses * whitePaint;
        System.out.println("Всего нужно банок белой краски " + allWhitePaint + " шт");
        long allBrownPaint = totalClasses * brownPaint;
        System.out.println("Всего нужно банок коричневой краски " + allBrownPaint + " шт");
        System.out.println("В школе, где " + totalClasses + " классов" + ", нужно " + allWhitePaint + " банок белой краски и " + allBrownPaint + " банок коричневой краски");

        System.out.println("Задание 6");
        long bananas = 5;
        System.out.println(bananas + " Банвнов");
        long weightOneBanana = 80;
        System.out.println("Вес одного банана " + weightOneBanana + " гр");
        long weightFiveBananas = bananas * weightOneBanana;
        System.out.println("Вес 5-и бананов " + weightFiveBananas + " гр");
        long milk = 200;
        System.out.println(milk + " мл молока");
        long mlMilk = 100;
        System.out.println(mlMilk + " мл для перевода в гр");
        long quantity = milk / mlMilk;
        System.out.println(quantity + " гр молока");
        long millilitersMilk = 105;
        System.out.println("Вес 100 мл молока " + millilitersMilk + " гр");
        long milkWeight = millilitersMilk * quantity;
        System.out.println("Вес " + milk + " мл молока " + milkWeight + " гр");
        long iceCreamSundae = 2;
        System.out.println("Всего пломбира " + iceCreamSundae + " шт");
        long briquette = 100;
        System.out.println("Брикет мороженного весит " + briquette + " гр");
        long totalWeightBriquettes = briquette * iceCreamSundae;
        System.out.println("Вес 2 брикетов мороженного " + totalWeightBriquettes + " гр");
        long eggs = 4;
        System.out.println("Всего яиц было " + eggs + " шт");
        long eggWeight = 70;
        System.out.println("Одно яйцо весит " + eggWeight + " гр");
        long weightAllEggs = eggWeight * eggs;
        System.out.println("Общий вес всех яиц " + weightAllEggs + " гр");
        double totalWeightSportsBreakfast = weightAllEggs + totalWeightBriquettes + milkWeight + weightFiveBananas;
        System.out.println("Общий вес спортзавтрака " + totalWeightSportsBreakfast + " гр");
        double oneKilogram = 1000;
        System.out.println("Вес одного килограмма " + oneKilogram + " гр");
        double kilogram = totalWeightSportsBreakfast / oneKilogram;
        System.out.println("Общий вес спортзавтрака " + kilogram + " кг");

        System.out.println("Задание 7");
        long advantage = 7;
        System.out.println("Перевес спортсмена на " + advantage + " кг");
        long kilo = 1000;
        System.out.println("Вес одного килограмма " + kilo + " гр");
        long sevenKilograms = advantage * kilo;
        System.out.println("Вес 7-и кг " + sevenKilograms + " гр");
        long minimalWeightLoss = 250;
        System.out.println("Минимальная потеря веса в день " + minimalWeightLoss);
        long minimumDays = sevenKilograms / minimalWeightLoss;
        System.out.println(minimumDays + " Дней нужно для того что бы сбросить вес по 250 гр в день");
        long weightLimit = 500;
        System.out.println("Максимальная потеря веса в день " + weightLimit);
        long maximumDays = sevenKilograms / weightLimit;
        System.out.println(maximumDays + " Дней нужно для того что бы сбросить вес по 500 гр в день");
        long averageNumberDays = (minimumDays + maximumDays) / 2;
        System.out.println("Среднее количество " + averageNumberDays + " дней нужно для того что бы сбросить вес на 7 кг");

        System.out.println("Задание 8");
        double salaryIncrease = 0.10;
        System.out.println("Процентная ставка на которую будем повышать зарплату сотрудникам " + salaryIncrease);

        double Masha = 67760;
        System.out.println("Зарплата Маши состовляет в месяц до повышения " + Masha + " Рублей");
        double annualIncomeBeforeRaisingMasha = Masha * 12;
        System.out.println("Годовой доход Маши до повышения: " + annualIncomeBeforeRaisingMasha + " рублей");
        double newMasha = Masha * (1 + salaryIncrease);
        double yearlyIncomeMasha = newMasha * 12;
        System.out.println("Новая зарплата Маши: " + newMasha + " рублей");
        System.out.println("Годовой доход Маши после повышения: " + yearlyIncomeMasha + " рублей");
        double Denis = 83690;
        System.out.println("Зарплата Дениса состовляет в месяц до повышения " + Denis + " Рублей");
        double annualIncomeBeforeRaisingDenis = Denis * 12;
        System.out.println("Годовой доход Дениса до повышения: " + annualIncomeBeforeRaisingDenis + " рублей");
        double newDenis = Denis * (1 + salaryIncrease);
        double yearlyIncomeDenis = newDenis * 12;
        System.out.println("Новая зарплата Дениса: " + newDenis + " рублей");
        System.out.println("Годовой доход Дениса после повышения: " + yearlyIncomeDenis + " рублей");
        double Kristina = 76230;
        System.out.println("Зарплата Кристины состовляет в месяц до повышения " + Kristina + " Рублей");
        double annualIncomeBeforeRaisingKristina = Kristina * 12;
        System.out.println("Годовой доход Кристины до повышения: " + annualIncomeBeforeRaisingKristina + " рублей");
        double newKristina = Kristina * (1 + salaryIncrease);
        double yearlyIncomeKristina = newKristina * 12;
        System.out.println("Новая зарплата Кристины: " + newKristina + " рублей");
        System.out.println("Годовой доход Кристины после повышения: " + yearlyIncomeKristina + " рублей");
    }
}